version: "3.8"

services:
  frontend:
    image: elilaura/compose-literature-frontend:v.1.0.0
    container_name: literature-frontend-compose
    environment:
      - NODE_OPTIONS=
      - PORT=3000
    expose:
      - "3000"
    restart: always
    networks:
      - literature-net

  nginx:
    image: nginx:alpine
    container_name: literature-nginx
    ports:
      - "3030:80"
    volumes:
      - - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
    restart: always
    networks:
      - literature-net

networks:
  literature-net:
    driver: bridge
